name: C++ CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cpp-thread-pool .

      - name: Run the binary inside Docker container (with timeout)
        run: |
          docker run --name my_container -d cpp-thread-pool
          timeout 30s docker wait my_container || echo "Timeout reached, force stopping..."
          docker logs my_container > run.log
          docker stop my_container || true
          
      - name: Copy logs from Docker container
        run: |
          docker cp my_container:/app/build.log build.log || echo "No build.log found"
          docker cp my_container:/app/run.log run.log || echo "No run.log found"
          docker rm -f my_container

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-and-run-logs
          path: |
            build.log
            run.log
